# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b9d6e9f15dee315d767846172016eec7bfa9cd5896134fd9e6490b9e7e3bdf0915a03bfe37c776df81368fa9192b610303134ae938c6ab32de9fe2d34138d96f

test:
  secret_key_base: 461529aa74514a63f5f1bc73e84df0ef79efe2bad350a8242f1402806fa0602517930c3074ffd176f789912f7c4863d943361c1828187d638f851163e13ed808

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
